# Generated by Django 4.2.13 on 2024-07-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
