# Generated by Django 4.2.13 on 2024-06-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_portfolio_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="tag_set",
        ),
    ]
