# Generated by Django 4.2.13 on 2024-07-06 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_delete_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="link_url",
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
